/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kaibo_ndklib_encrypt_EncryptUtils */

#ifndef _Included_com_kaibo_ndklib_encrypt_EncryptUtils
#define _Included_com_kaibo_ndklib_encrypt_EncryptUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kaibo_ndklib_encrypt_EncryptUtils
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kaibo_ndklib_encrypt_EncryptUtils_encrypt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_kaibo_ndklib_encrypt_EncryptUtils
 * Method:    decrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kaibo_ndklib_encrypt_EncryptUtils_decrypt
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
